#!/bin/sh
HOOKS=""

REPOS="$1"
REV="$2"
USER=$(svnlook author -r $REV $REPOS)
TEXT=$(svnlook log -r $REV $REPOS)
COUNT=$(svnlook changed $REPOS -r $REV | wc -l)
BRANCH=$(svnlook dirs-changed -r $REV $REPOS)

payload="{\"text\": \"$TEXT\", \"user\": \"$USER\", \"branch\": \"$BRANCH\", \"count\": \"$COUNT\",\"rev\":\"$REV\" }"

curl -fsSL -X "POST" "$HOOKS" \
	 -H "Content-Type: application/json" \
	 -d "$payload"
